name: CICD Pipeline

on:
  push:

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Super-linter
        uses: super-linter/super-linter@v7.4.0 # x-release-please-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # used to

      - name: NodeJS setup
        uses: actions/setup-node@v4 # Setup nodejs
        with:
        # LTS Version
          node-version: 22

      - name: Frontend setup
        # Switch to frontend directory
        working-directory: ./front
        run: npm ci
        
      - name: Build frontend
        working-directory: ./front
        run: npm run build

      - name: Backend setup
        working-directory: ./server
        run: npm ci
  synk:
    name: Snyk scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Snyk
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: test ./server --json
