name: CICD Pipeline

on:
  push:

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Super-linter
        uses: super-linter/super-linter@v7.4.0 # x-release-please-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # used to

      - name: NodeJS setup
        uses: actions/setup-node@v4 # Setup nodejs
        with:
        # LTS Version
          node-version: 22

      - name: Frontend setup
        # Switch to frontend directory
        working-directory: ./front
        run: npm ci
        
      - name: Build frontend
        working-directory: ./front
        run: npm run build

      - name: Backend setup
        working-directory: ./server
        run: npm ci
  synk:
    name: Snyk scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Snyk
      run: npm install -g snyk
    - name: Auth snyk
      run: snyk auth "${{ secrets.SNYK_TOKEN }}"
      
    - name: Run snyk
      run: snyk test --all-projects
  zap:
    name: Zap scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        working-directory: ./server
        run: npm ci
        
      - name: Install dependencies
        working-directory: ./front
        run: npm ci

      - name: Create .env file
        working-directory: ./server
        run: echo "DB_URI=${{ secrets.DB_URI }}" >> .env && echo "PORT=${{ secrets.PORT }}" >> .env

      - name: Start backend
        working-directory: ./server
        run: nohup npm start

      - name: Start frontend
        working-directory: ./front
        run: nohup npm start
          
      - name: ZAP scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://localhost:3000/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
          
